---
title: "Masters Homework 2"
author: "JEHAN BISTA"
date: "7/21/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


>- Find summary information about the total blood mercury levels in our NYC HANES data (hint: names(nyc) will call the names of each column). What is the max value, what is the minimum value.  

```
nyc <- read.csv("NYC_HANES_DIAB.csv")

head(nyc)     # Shows the first few rows of the dataset
names(nyc)    # Lists the column names
str(nyc)      # Displays the structure and data types of all columns

summary(nyc$MERCURYTOTALBLOOD)
min(nyc$MERCURYTOTALBLOOD, na.rm = TRUE)
max(nyc$MERCURYTOTALBLOOD, na.rm = TRUE)

```

>- Bonus/Challenge: What is the Standard Deviation and skewness of the blood mercury?

```
if (!require(e1071)) install.packages("e1071")
library(e1071)

sd(nyc$MERCURYTOTALBLOOD, na.rm = TRUE)
skewness(nyc$MERCURYTOTALBLOOD, na.rm = TRUE)

```

>- Install a package and load, such as "ggplot2" or "dplyr"

```
if (!require(dplyr)) install.packages("dplyr")
library(dplyr)

```

>- What two commands are needed to install and use a package in R?

```
install.packages("ggplot2")
library(ggplot2)

```

>- When you read in a .csv file into R, what class is the object that you read in (like nyc)?

Answer: The class of the object nyc will be "data.frame"
```
class(nyc)

```

>- What command can you use to determine what type of data is in a column?

```
Answer: You can use the 'class' and 'typeof' commands. Class shows you the type of data (ex. numeric), whereas typeof shows how the data is stored in memory. 

```

>- Provide a command to find the type of data in the DX_DBTS column of nyc. 

```
class(nyc$DX_DBTS)
typeof(nyc$DX_DBTS)

```

>- Provide the same command the type of data but use the other way of indexing from what you did above. 

```
class(nyc[["DX_DBTS"]])

```

>- What would happen if we had chosen the first 4 columns of NYC HANES and made a matrix? What would the class of the cells in this matrix be? Why?

```
mat <- as.matrix(nyc[, 1:4])
class(mat) 
typeof(mat[1, 1])

```


>- If we make a vector,vec<- c(3,9,4,7,8,9), and multiply it by WannaMatrix, what is the value in the third row, third column? 

```
vec <- c(3, 9, 4, 7, 8, 9)
WannaMatrix <- nyc[5:10, 6:9]
WannaMatrix <- as.matrix(WannaMatrix,nrow = 6, ncol = 4)
result <- vec * WannaMatrix
result[3, 3]

```

>- What happens if instead we made a vector vec2 <- c(3,9,4,7,8) and multiply it by WannaMatrix, what is the third row, third column value? What is going on? 

Answer: Because the vector has 5 elements and WannaMatrix has 6 rows, R will recycle the vector, using the first value again to perform the calculation. 

```
vec2 <- c(3, 9, 4, 7, 8)
result2 <- vec2 * WannaMatrix
result2[3, 3]

```

>- Look up the arguments for read.csv

```
help(read.csv)

```

>- Use apply() to find the median value of CADMIUM, LEAD CHOLESTEROLTOTAL, GLUCOSESI, CREATININESI, and CREATININE

```
selected_cols <- nyc[, c("CADMIUM", "LEAD", "CHOLESTEROLTOTAL", "GLUCOSESI", "CREATININESI", "CREATININE")]

apply(selected_cols, 2, median, na.rm = TRUE)

```

>- Do the same using sapply()

```
selected_vars <- c("CADMIUM", "LEAD", "CHOLESTEROLTOTAL", "GLUCOSESI", "CREATININESI", "CREATININE")

sapply(nyc[, selected_vars], median, na.rm = TRUE)

```

>- Use a for loop to find the median value of columns 16:19

```
medians <- c()

for (i in 16:19) {
  col_name <- names(nyc)[i]
  med_value <- median(nyc[[i]], na.rm = TRUE)
  
  medians[col_name] <- med_value
}

medians

```

>- Make a for loop to find the standard deviation (hint sd() ) of CHOLESTEROLTOTAL, GLUCOSESI, CREATININESI, AND CREATININE

```
cols <- c("CHOLESTEROLTOTAL", "GLUCOSESI", "CREATININESI", "CREATININE")

sds <- c()

for (col in cols) {
  sds[col] <- sd(nyc[[col]], na.rm = TRUE)
}

sds

```

>- Bonus/Challenge Create a vector in which to put the standard deviations 

```
cols <- c("CHOLESTEROLTOTAL", "GLUCOSESI", "CREATININESI", "CREATININE")

std_devs <- numeric(length(cols))        # creates a numeric vector of correct length
names(std_devs) <- cols                  # names each position after the column

for (i in seq_along(cols)) {
  std_devs[i] <- sd(nyc[[cols[i]]], na.rm = TRUE)
}

std_devs

```

>- Use ifelse to create a new variable of high and normal A1C dichotomizing with 7 as a threshold for high levels

```
nyc$A1C_status <- ifelse(nyc$A1C >= 7, "high", "normal")
table(nyc$A1C_status, useNA = "ifany")

```
###################################################################################OPTIONAL##############################################################################################

>- Subset to only have females (gender == "female")

```
nyc_female <- nyc[nyc$GENDER == 2, ]
head(nyc_female)
nrow(nyc_female)
table(nyc_female$GENDER)

```


>- Create a subset of males and find the median total cholesterol level

```
nyc_male <- nyc[nyc$GENDER == 1, ]
median(nyc_male$CHOLESTEROLTOTAL, na.rm = TRUE)

```

>- Try to create a summary of the mean A1C using two factors, GENDER and DX_DBTS

```
aggregate(A1C ~ GENDER + DX_DBTS, data = nyc, FUN = mean, na.rm = TRUE)

```

Find the class of the first three columns of data. What are they?

```
sapply(nyc[, 1:3], class)

```

